spring:
  data:
    mongodb:
#      uri: mongodb_uri_here
      database: blogDB
  application:
    name: blogDB

blogapp:
  jwt:
#    jwtSecret: secret_here
#    jwtExpirationMs: expiration_here

server:
  port: 8080