spring:
  data:
    mongodb:
      uri: mongodb+srv://a4anurag13:091MmVlzOvDENpjZ@cluster0.dozbqne.mongodb.net/
      database: blogDB
  application:
    name: blogDB
  security:
    user:
      password: TestUser1
blogapp:
  jwt:
    jwtSecret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    jwtExpirationMs: 86400000




server:
  port: 8080